---
title: "Modules"
format: 
  html:
    toc: true
knitr:
  opts_chunk: 
    collapse: true
    comment: "" 

execute:
  echo: true

vignette: >
  %\VignetteIndexEntry{Modules}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| label: setup
#| include: false
library(lobstr)
```

## Application modules 

The application's modules in the [`28_chores`](https://github.com/mjfrigaard/sap/tree/28_chores) branch. 

```{r}
#| eval: false
#| collapse: true
list.files("../R/", pattern = "mod_")
```

```{verbatim}
├── mod_awards_point.R
├── mod_awards_tbl.R
├── mod_awards_vars.R
├── mod_compare_point.R
├── mod_compare_vars.R
├── mod_counts_bar.R
├── mod_counts_tbl.R
├── mod_counts_vars.R
├── mod_counts_vbox.R
├── mod_counts_waffle.R
├── mod_dist_box.R
├── mod_dist_raincloud.R
├── mod_dist_tbl.R
└── mod_dist_vars.R
```


```{r}
#| echo: false
lobstr::ast(
  launch_app(
    display_type(),
    nav_ui(
      mod_compare_vars_ui(),
      mod_compare_point_ui(),
      mod_counts_vars_ui(),
      mod_counts_vbox_ui(),
      mod_counts_bar_ui(),
      mod_counts_waffle_ui(),
      mod_counts_tbl_ui(),
      mod_dist_vars_ui(),
      mod_dist_box_ui(),
      mod_dist_raincloud_ui(),
      mod_dist_tbl_ui(),
      mod_awards_vars_ui(),
      mod_awards_point_ui(),
      mod_awards_tbl_ui()
    ),
    nav_server(
      mod_compare_vars_server(),
      mod_compare_point_server(),
      mod_counts_vars_sever(),
      mod_counts_vbox_server(),
      mod_counts_bar_server(),
      mod_counts_waffle_server(),
      mod_counts_tbl_server(),
      mod_dist_vars_server(),
      mod_dist_box_server(),
      mod_dist_raincloud_server(),
      mod_dist_tbl_server(
        dist_var_summary()
      ),
      mod_awards_vars_server(),
      mod_awards_point_server(
        create_movie_awards()
      ),
      mod_awards_tbl_server()

    )
  )
)
```