---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Install:

``` r
install.packages('pak')
pak::pak('mjfrigaard/shinyrPkgs')
```

Load:

```{r setup}
library(shinyrPkgs)
```

You can launch the following apps from `shinyrPkgs`:

1. *Launches the standard application in the viewer pane*

    ``` r
    shinyrPkgs::launch_app()
    ```

2. *Launch the standard application in test mode (in the Window)*

    ``` r
    launch_app(options = list(test.mode = TRUE), run = 'w')
    ```

3. *Launch the `bslib` version of the applictation in test mode (in the browser)*

    ``` r
    launch_app(options = list(test.mode = TRUE), run = 'b', bslib = TRUE)
    ```

4. _Launch a 'development' version of the applicationn (with data `ggplot2movies` in the **Viewer** pane)_

    ``` r
    ggp2_launch_app(run = 'p')
    ```
